### PR TITLE
Openshift integration

### PR DESCRIPTION
**Pull request by DanielePalaia**
Adding finalizers permissions in clusterrole definition

This closes #

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed
**Note to contributors:** remember to re-generate client set if there are any API changes

### CODE REVIEW

**Review by ChunyiLyu — CHANGES_REQUESTED** [review]
I think `update` as one verb should be enough for finalizer management. This is what we have for cluster operator: https://github.com/rabbitmq/cluster-operator/blob/main/controllers/rabbitmqcluster_controller.go#L82

Could you please take a look what's the minimal set of verb we need instead of adding all of them? Thanks!

**Comment by DanielePalaia** [comment]
@ChunyiLyu I made some tests and yes update should be enough! Fixed the commit thanks!

**Review by Zerpet — APPROVED** [review]
Looks good with the new changes. I'll wait for @ChunyiLyu to confirm and give approval ✅

**Review by ChunyiLyu — APPROVED** [review]
Thank you for updating 😺

**Pull request merged**
